apiVersion: v2
name: vault-unsealer
description: A kubernetes controller that can auto unseal vault pods.
type: application
version: 0.1.6
appVersion: v0.1.6
icon: https://emojigraph.org/media/google/seal_1f9ad.png
sources:
  - https://github.com/bakito/vault-unsealer
maintainers:
  - name: bakito
    url: https://github.com/bakito
