apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vault-unsealer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "vault-unsealer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
  {{- include "vault-unsealer.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
      {{- include "vault-unsealer.selectorLabels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{ . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{ . | toYaml | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "vault-unsealer.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: '{{ .Values.image.repository }}:{{- .Values.image.tag | default .Chart.AppVersion }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /opt/go/vault-unsealer
          env:
            - name: UNSEALER_DEPLOYMENT_NAME
              value: {{ include "vault-unsealer.fullname" . }}
            - name: UNSEALER_SERVICE_NAME
              value: {{ include "vault-unsealer.fullname" . }}
            - name: UNSEALER_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: UNSEALER_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: UNSEALER_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          {{- if or (eq (.Values.sharedCache.enabled | toString) "true") (eq (.Values.leaderElection.enabled | toString) "true")  }}
          args:
          {{- if eq (.Values.sharedCache.enabled | toString) "true" }}
            - '-shared-cache'
          {{- end }}
          {{- if eq (.Values.leaderElection.enabled | toString) "true" }}
            - '-leader-elect'
          {{- end }}
          {{- end }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 8080
              name: metrics
          {{- with .Values.securityContext }}
          securityContext:
          {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
