apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault-unsealer.fullname" . }}
  labels:
  {{- include "vault-unsealer.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: metrics
  selector:
    {{- include "vault-unsealer.selectorLabels" . | nindent 6 }}
