apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vault-unsealer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "vault-unsealer.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
  {{- include "vault-unsealer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "vault-unsealer.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "vault-unsealer.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /opt/go/vault-unsealer
          env:
            - name: OPERATOR_NAME
              value: {{ include "vault-unsealer.fullname" . }}
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 8080
              name: metrics
            {{- if .Values.webhook.enabled }}
            - containerPort: 9443
              name: webhook
          {{- end }}
          {{- if .Values.webhook.enabled  }}
          volumeMounts:
            - mountPath: /opt/go/certs
              name: "webhook-certs"
              readOnly: true
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.webhook.enabled }}
      volumes:
        - name: "webhook-certs"
          secret:
            defaultMode: 420
            secretName: {{ include "vault-unsealer.webhookCertSecretName" . }}
      {{- end }}
