{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vault-unsealer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{ include "vault-unsealer.labels" . | nindent 4 }}
  {{- end -}}
