name: govulncheck
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule: # daily at 02:34 UTC
    - cron: '34 02 * * *'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  govulncheck:
    name: Check Vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Check Vulnerabilities
        run: make check-vulnerabilities
